# Generated by Django 4.1.7 on 2023-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat', models.CharField(max_length=20)),
                ('kcol', models.IntegerField()),
            ],
        ),
    ]
