# Generated by Django 4.1.7 on 2023-02-19 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 22, 17, 0, 908455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='karomodel',
            name='daycolor',
            field=models.CharField(choices=[('secondary', 'MON~Fri'), ('primary', 'SATURDAY'), ('danger', 'SUNDAY')], default='secondary', max_length=10),
        ),
    ]
