# Generated by Django 4.1.7 on 2023-02-20 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karo', '0002_karomodel_date_karomodel_daycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='karomodel',
            name='goleKcol',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 11, 41, 15, 275828, tzinfo=datetime.timezone.utc)),
        ),
    ]
