# Generated by Django 4.1.7 on 2023-02-20 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karo', '0003_karomodel_golekcol_alter_karomodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='karomodel',
            name='addkcol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 20, 55, 57, 14697, tzinfo=datetime.timezone.utc)),
        ),
    ]
