# Generated by Django 4.1.7 on 2023-02-21 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karo', '0004_karomodel_addkcol_alter_karomodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karomodel',
            name='addkcol',
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 19, 50, 22, 956265, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='kcol',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
