# Generated by Django 4.1.7 on 2023-02-24 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karo', '0005_remove_karomodel_addkcol_alter_karomodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 15, 51, 48, 320902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='daycolor',
            field=models.CharField(choices=[('secondary', 'NIGHT'), ('primary', 'DAYTIME'), ('danger', 'MORNING')], default='secondary', max_length=10),
        ),
        migrations.AlterField(
            model_name='karomodel',
            name='goleKcol',
            field=models.IntegerField(default=0),
        ),
    ]
